### ISSUE TITLE
Python wrapper could benefit from utilizing Cython

### ISSUE THREAD

**Issue by tenko** [cwida/duckdb#435]
Looking at the current python wrappers with direct calling of the CPython API  I put together a Cython version for comparison at : 
 
  https://gist.github.com/tenko/93ffd3d69d20ebd95522b361f90f7f16

I tried to follow the dbapi2 as closely as possible and in addition support numpy and the python datetime module. It seems to work OK with some simple manual tests.

Benefits are definitive readability and also possible correctness as reference counting is removed from the equation. 

Downside is adding a dependency on Cython, but it is possible to include the generated files in the repository.

I can create a PR if this is of interest .

Runar

**Comment by hannesmuehleisen** [comment]
That looks pretty good! I wonder how we would implement fetchdf() efficiently in this context? Did you do performance comparisons by chance?

**Comment by tenko** [comment]
I updated the code with creation of Pandas dataframe object via numpy masked array.
Not heavy tested, but seems to work OK. 

This should be fairly efficient as the python buffer protocol is utilized and therefore I
assume no data duplication should happen. 

With regards to general performance I have not performed any tests, just implemented code
based on intuition of what should be efficient. For example:

 - Perhaps a custom cursor row object should be implemented instead of return a tuple
 - Check if the buffer interface is used as expected
 - Varchar is converted to python strings which is not optimal. Not sure if there is any
   good alternative here.

Also Cython can be used directly and the Prepared class was added for that in mind.
The bind methods can be invoked with typed arguments without involving any Python
API calls and should be close to C in speed.

PS : The C Api definitions was added to the top of the file, so it is possible to build.

**Comment by Mytherin** [comment]
Thanks for the effort! I think the code looks good, but I'm not sure if DuckDB is a good target for Cython. I thought about it and I have a number of doubts:

* The additional dependency as you mentioned seems like it could provide difficulties for people that want to work on the Python library
* Debugging seems like it would be more difficult, as there are now multiple layers of code (the converted C code and the original Cython code) rather than only a single layer of C++ code
* Your example code seems to use the C API, but as DuckDB is natively written in C++ we would prefer to interface with it using the C++ API. The C API performs a bunch of data materialization and type conversions at the border which we could avoid by interfacing directly with the C++ API. Can Cython cleanly interface with C++, including modern features such as smart pointers?
* How does Cython work with Python 2/3? Can it generate files that are "Python oblivious", or do you need to generate different files for each version? If it is the latter, this is problematic because we would need to check in and maintain two different source files.

Overall I like the way that it looks but I think it introduces a number of problems and headaches. From my perspective Cython seems mainly useful for programs that are written in the other direction, i.e. programs that are mostly Python, but want a bit of C code sprinkled in for performance reasons. DuckDB is the other way around, mostly C++ code, with a small number of calls to Python for data conversions (namely C++ types to Python types and back). If I look at the Cython code I see many times more calls to the DuckDB C interface than to Python functions. To me that signifies that Cython is the wrong tool to use here. 

The code definitely looks more readable, but I think a lot of readability issues can also be fixed in the C++ layer by making better use of wrapper objects and functions. That can also take care of manual reference counting there. Currently most of the messy code is inherited from the Python SQLite library.

I'm not entirely opposed to it, but my initial instinct is that it creates more problems than it solves. Thanks for all the effort and the example implementation though! It's very useful to think about the different trade-offs here.

**Comment by tenko** [comment]
Some comments:

- The C API was chosen for simplicity. Cython have good support for C++ constructs and the code could be converted with some minor work.
  Ref. https://cython.readthedocs.io/en/latest/src/userguide/wrapping_CPlusPlus.html
 
 - A single Cython source file can support both python 2 and 3. You also can support both 
 version from a single generated source file.

 - I do not have any experience in debugging Cython, but the documentation has information on this and it seem to be well developed:
   Ref. https://cython.readthedocs.io/en/latest/src/userguide/debugging.html

With regards to keeping the code base C++ only, there is a header only library called pybind11 which seems to be very complete with numpy support etc. Could be a good fit.

The only downside with pybind11 is that we loose the possibility to use Cython typed construct. With Cython I can just issue a "cimport duckdb" and annotate a Python file with the relevant type definitions and recompile the code for speed.  This is fairly popular method in the to accelerate code instead of going the route through C/C++.

It is all a trade off in features and future maintenance.

I am willing to convert the Cython code to the C++ API.
This could also can be interesting for benchmark testing and general comparison.

**Comment by Mytherin** [comment]
Thanks again for the additional information! Cython indeed looks very complete, and very nice that it also supports C++. But I am still not a big fan of Cython for this use case. I think Cython is great if you are writing mostly Python code, but our code is mostly C++. That means that you are now writing tons of C++ code, but writing it using Cython cdef types and such, and to me that seems like a lot more trouble than just writing C++ code to begin with. Cython seems more useful if you are planning on writing a lot of Python code with a small amount of C++ code mixed in for performance. That is certainly a valid use case, but it is not what we are trying to do here.

I was not aware of pybind11, I think that looks excellent! We can keep the code in C++ without having to manually deal with the ugliness of the CPython interface and without having to deal with reference counting and such. I think this suits our use case extremely well, and I think it is great that it is a dependency-free library. I think it is a great idea to convert our existing Python library to one that uses pybind11. It seems like that will clean up the code a lot and make it a lot more maintainable.

Thanks again for the information and for the effort. It has been very helpful!

**Comment by tenko** [comment]
Glad the information and comments was useful.

I was thinking it could be a good idea to reuse the test suite for the sqlite module included in CPython if possible : 

https://github.com/python/cpython/tree/master/Lib/sqlite3/test

The test suite is quite extensive and tests many corner cases. This would ensure the bindings are a drop in for the python sqlite module.

**Comment by Mytherin** [comment]
That is an excellent idea! Thanks for the link. We should certainly integrate them into our test suite.

**Comment by hannesmuehleisen** [comment]
Tracking the tests in #469 and closing here

**Comment by hannesmuehleisen** [comment]
@enko 

> With regards to keeping the code base C++ only, there is a header only library called pybind11 which seems to be very complete with numpy support etc. Could be a good fit.

Thanks for this tip, this was an excellent suggestion and we have started switching the Python API to pybind11. See the `pybind` branch if you are interested.

**Comment by tenko** [comment]
I will take a closer look at it as soon as I have some time. The code looks very clean and easy to read compared to the original version. I am afraid I am not fluent enough in C++ to be of any implementation help, but I can comment on the code etc., 

Looking at the fetch all method : is the size of the result set known? If so, it could be advantageous to pre-allocate the list to the correct size before the loop.

Best regards
